version: '3'

services:
  #controller:
  #  container_name: controller
  #  image: gr2/controller
  #  environment:
  #    - ID=ctrl1
  #    - CS=activemq
  #    - CS_PORT=5672
  #  depends_on:
  #    - activemq

  ctlms:
    container_name: ctlms
    image: gr2/ctlms
    environment:
      - RABBIT_HOST=activemq
    depends_on:
      - activemq
      - mymongo

  activemq:
    container_name: activemq
    image: rabbitmq:3.6
    ports:
      - 15672:15672
      - 5672:5672

  mymongo:
    container_name: mymongo
    image: mongo:latest
    ports:
      - 27017:27017

networks:
  default:
    external:
      name: street_network
