version: "3"

services:
  activemq:
    container_name: activemq
    image: rabbitmq:3.6
    ports:
      - 15672:15672
      - 5672:5672
    network_mode: bridge

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    network_mode: bridge
