version: "3"

services:
  activemqStage:
    container_name: activemqStage
    image: rabbitmq:3.6
    ports:
      - 15672:15672
      - 5672:5672
    network_mode: bridge

  mymongoStage:
    container_name: mymongoStage
    image: mongo:latest
    ports:
      - 27017:27017
    network_mode: bridge
